import type { Metadata } from "next";
import { Outfit, Ovo } from "next/font/google";
import "./globals.css";

const Outfits = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const Ovos = Ovo({
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Portfolio - GreatStack",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth dark">
      <body
        className={`${Outfits.className} ${Ovos.className} antialiased leading-8 overflow-x-hidden dark:bg-[#2a004a] dark:text-white `}
      >
        {children}
      </body>
    </html>
  );
}
